apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: payment:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50052
        env:
        - name: DB_HOST
          value: postgres-service
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: msgo
        - name: DB_PASSWORD
          value: msgo123
        - name: DB_NAME
          value: msgo_db